#!/bin/bash

### You can change some default settings down here if you want to

# Default audio splice duration in seconds (for AudD recognition API)
SPLICE_DURATION=10

# Relative path for AudD api token for audio recognition
API_TOKEN_FILE=api_token

### ------------------------------------------------------------

print_help () {
	echo 'USAGE: tag-ninja [path_to_audio_file]'
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] 
then
	print_help
	exit 0
fi

if [ -z "$1" ]
then
	echo "Please give the path to the audio file you want to tag."
	print_help
	exit 1
fi

if [ -n "$2" ]
then
	echo "Too many arguments."
	print_help
	exit 1
fi


# Checking if given file exists 
if [ ! -f $1 ]
then
	echo "File does not exist."
	exit 1
fi

# Creating temporary files for storing data
AUDIO_SPLICE_FLAC=$(mktemp /tmp/tag-ninja-XXXXXXXX.flac)
RECOGNIZED_JSON=$(mktemp /tmp/tag-ninja-XXXXXXXX.json)
FLAC_TAG=$(mktemp /tmp/tag-ninja-XXXXXXXX.tag)

# Splicing audio file
ffmpeg -hide_banner -loglevel panic -y -ss 0 -i $1 -t $SPLICE_DURATION -c copy $AUDIO_SPLICE_FLAC

# Requesting song recognition from AudD
curl -X POST -F "api_token=$(cat $API_TOKEN_FILE)" -F "file=@$AUDIO_SPLICE_FLAC" -F "return=spotify" https://api.audd.io/ | jq > $RECOGNIZED_JSON

# Getting track info from response json
TAG_ARTIST=$(jq ".result.artist" $RECOGNIZED_JSON)
TAG_ALBUM=$(jq ".result.album" $RECOGNIZED_JSON)
TAG_SONGTITLE=$(jq ".result.title" $RECOGNIZED_JSON)
TAG_RELEASEDATE=$(jq ".result.release_date" $RECOGNIZED_JSON)
TAG_TRACK_NUMBER=$(jq ".result.spotify.track_number" $RECOGNIZED_JSON)
TAG_TOTAL_TRACKS=$(jq ".result.spotify.album.track_number" $RECOGNIZED_JSON)

# Building flac tag
echo "TRACKTOTAL=$TAG_TOTAL_TRACKS" >> $FLAC_TAG
echo "TRACKNUMBER=$TAG_TRACK_NUMBER" >> $FLAC_TAG
echo "TITLE=$TAG_SONGTITLE" > $FLAC_TAG
echo "ARTIST=$TAG_ARTIST" >> $FLAC_TAG
echo "ALBUM=$TAG_ALBUM" >> $FLAC_TAG
echo "DATE=$TAG_RELEASEDATE" >> $FLAC_TAG

# Removing quotations
sed -i 's/\"//g' $FLAC_TAG

# Adding tag to .flac file
metaflac --remove-all-tags $1
metaflac --import-tags-from=$FLAC_TAG $1

rm -f /tmp/tag-ninja* 
exit 0
